version: "3"
services:
  db:
    container_name: mysqlAMTp2
    build: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
  
  authapi:
    container_name: authapiAMT
    build: auth api/docker
    restart: always
    depends_on:
      - db
    ports:
      - "9000:9000"

  bookingapi:
    container_name: bookingapiAMT
    build: booking api/docker
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"



